In [1]:
import numpy

In [2]:
numpy.array([3,5,8,17])

array([ 3,  5,  8, 17])

In [3]:
numpy.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
numpy.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
numpy.arange(5)

array([0, 1, 2, 3, 4])

In [6]:
numpy.arange(6,12)

array([ 6,  7,  8,  9, 10, 11])

In [7]:
numpy.arange(6,12,2)

array([ 6,  8, 10])

In [8]:
numpy.linspace(6,12,3)

array([ 6.,  9., 12.])

In [9]:
numpy.linspace(6,12)

array([ 6.        ,  6.12244898,  6.24489796,  6.36734694,  6.48979592,
        6.6122449 ,  6.73469388,  6.85714286,  6.97959184,  7.10204082,
        7.2244898 ,  7.34693878,  7.46938776,  7.59183673,  7.71428571,
        7.83673469,  7.95918367,  8.08163265,  8.20408163,  8.32653061,
        8.44897959,  8.57142857,  8.69387755,  8.81632653,  8.93877551,
        9.06122449,  9.18367347,  9.30612245,  9.42857143,  9.55102041,
        9.67346939,  9.79591837,  9.91836735, 10.04081633, 10.16326531,
       10.28571429, 10.40816327, 10.53061224, 10.65306122, 10.7755102 ,
       10.89795918, 11.02040816, 11.14285714, 11.26530612, 11.3877551 ,
       11.51020408, 11.63265306, 11.75510204, 11.87755102, 12.        ])

In [10]:
len(numpy.linspace(6,12))

50

In [12]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(a)
print("dimension of array=",arr.ndim)

dimension of array= 2


In [13]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(a)
print("shape of array=",arr.shape)

shape of array= (3, 3)


In [14]:
arr=np.ones((4,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
arr=np.eye((3))
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
arr=np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [17]:
arr=np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [18]:
arr=np.diag([2,3,3,4])
np.diag(arr)

array([2, 3, 3, 4])

In [19]:
arr=np.random.randint(1,10,3)
arr

array([6, 6, 2])

In [20]:
arr=np.random.rand(5)
arr

array([0.57384757, 0.91859566, 0.05539968, 0.54922641, 0.0394697 ])

In [21]:
arr=np.random.rand(2,3)
arr

array([[0.6199324 , 0.51446172, 0.12443365],
       [0.9896397 , 0.08797888, 0.62436063]])

In [22]:
np.arange(0,100,6)

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96])

In [23]:
Arr2=np.random.randint(10,size=(4,3))
Arr2

array([[0, 9, 3],
       [4, 6, 3],
       [4, 1, 9],
       [6, 2, 4]])

In [26]:
Arr1=np.random.randint(20,size=(4,3))
Arr1

array([[ 1,  6,  1],
       [18,  4,  6],
       [ 2,  8, 18],
       [14,  0,  3]])

In [25]:
Arr2=np.random.randint(10,size=(4,3))
Arr2

array([[1, 6, 9],
       [1, 9, 6],
       [0, 8, 0],
       [0, 9, 9]])

In [27]:
Arr3=np.concatenate((Arr1,Arr2),axis=0) 
Arr3

array([[ 1,  6,  1],
       [18,  4,  6],
       [ 2,  8, 18],
       [14,  0,  3],
       [ 1,  6,  9],
       [ 1,  9,  6],
       [ 0,  8,  0],
       [ 0,  9,  9]])

In [28]:
np.split(Arr3,2)

[array([[ 1,  6,  1],
        [18,  4,  6],
        [ 2,  8, 18],
        [14,  0,  3]]),
 array([[1, 6, 9],
        [1, 9, 6],
        [0, 8, 0],
        [0, 9, 9]])]

In [30]:
np.hsplit(Arr3,3)

[array([[ 1],
        [18],
        [ 2],
        [14],
        [ 1],
        [ 1],
        [ 0],
        [ 0]]),
 array([[6],
        [4],
        [8],
        [0],
        [6],
        [9],
        [8],
        [9]]),
 array([[ 1],
        [ 6],
        [18],
        [ 3],
        [ 9],
        [ 6],
        [ 0],
        [ 9]])]

In [31]:
Arr4=Arr3.reshape(3,8)
Arr4

array([[ 1,  6,  1, 18,  4,  6,  2,  8],
       [18, 14,  0,  3,  1,  6,  9,  1],
       [ 9,  6,  0,  8,  0,  0,  9,  9]])

In [32]:
Arr3[0:5,2]

array([ 1,  6, 18,  3,  9])

In [33]:
Arr3>10

array([[False, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [37]:
Arr4

array([[ 1,  6,  1, 18,  4,  6,  2,  8],
       [18, 14,  0,  3,  1,  6,  9,  1],
       [ 9,  6,  0,  8,  0,  0,  9,  9]])

In [35]:
np.add(Arr4,1)

array([[ 2,  7,  2, 19,  5,  7,  3,  9],
       [19, 15,  1,  4,  2,  7, 10,  2],
       [10,  7,  1,  9,  1,  1, 10, 10]])

In [36]:
np.multiply(Arr4,2)

array([[ 2, 12,  2, 36,  8, 12,  4, 16],
       [36, 28,  0,  6,  2, 12, 18,  2],
       [18, 12,  0, 16,  0,  0, 18, 18]])

In [38]:
Arr6=np.random.randint(5,size=(3,4))
Arr6

array([[3, 2, 4, 2],
       [1, 4, 2, 4],
       [4, 3, 2, 4]])

In [39]:
Arr7=np.random.randint(15,size=(3,4))
Arr7

array([[ 8, 14,  6,  3],
       [ 1,  0,  3, 13],
       [ 5,  3,  0,  6]])

In [40]:
np.add(Arr6,Arr7)

array([[11, 16, 10,  5],
       [ 2,  4,  5, 17],
       [ 9,  6,  2, 10]])

In [41]:
Arr8=np.add(Arr6,1)
Arr8

array([[4, 3, 5, 3],
       [2, 5, 3, 5],
       [5, 4, 3, 5]])

In [42]:
Arr9=np.add(Arr7,1)
Arr9

array([[ 9, 15,  7,  4],
       [ 2,  1,  4, 14],
       [ 6,  4,  1,  7]])

In [43]:
Arr10=np.divide(Arr8,Arr9)
Arr10

array([[0.44444444, 0.2       , 0.71428571, 0.75      ],
       [1.        , 5.        , 0.75      , 0.35714286],
       [0.83333333, 1.        , 3.        , 0.71428571]])

In [44]:
np.ceil(Arr10)

array([[1., 1., 1., 1.],
       [1., 5., 1., 1.],
       [1., 1., 3., 1.]])

In [45]:
np.mean(Arr9,axis=1)

array([8.75, 5.25, 4.5 ])

In [46]:
Arr9.min()

1

In [47]:
Arr9.max()

15

In [48]:
np.var(Arr9)

19.472222222222225

In [49]:
np.std(Arr9,axis=1)

array([4.02336923, 5.16599458, 2.29128785])

In [50]:
a
Arr11=np.append(Arr8,(1,2,3,4))
Arr11

array([4, 3, 5, 3, 2, 5, 3, 5, 5, 4, 3, 5, 1, 2, 3, 4])

In [51]:
Arr10=np.divide(Arr8,Arr9)
Arr10

array([[0.44444444, 0.2       , 0.71428571, 0.75      ],
       [1.        , 5.        , 0.75      , 0.35714286],
       [0.83333333, 1.        , 3.        , 0.71428571]])

In [52]:
np.subtract(Arr9,Arr8)

array([[ 5, 12,  2,  1],
       [ 0, -4,  1,  9],
       [ 1,  0, -2,  2]])

In [53]:
np.square(Arr7,Arr8)

array([[ 64, 196,  36,   9],
       [  1,   0,   9, 169],
       [ 25,   9,   0,  36]])

In [54]:
np.array_equal(Arr9,Arr9)

True

In [55]:

np.array_equal(Arr9,Arr1)

False